config/routes.rb
KoozyCollection::Application.routes.draw do
  resources :koozy_tags

  resources :koozies

  resources :styles

  resources :tags

end

app/models/koozy.rb
class Koozy < ActiveRecord::Base
  belongs_to :style
end

app/models/koozy_tag.rb
class KoozyTag < ActiveRecord::Base
  belongs_to :koozy
  belongs_to :tag
end

app/models/style.rb
class Style < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/koozies_controller.rb
class KooziesController < ApplicationController
  # GET /koozies
  # GET /koozies.xml
  def index
    @koozies = Koozy.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @koozies }
    end
  end

  # GET /koozies/1
  # GET /koozies/1.xml
  def show
    @koozy = Koozy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @koozy }
    end
  end

  # GET /koozies/new
  # GET /koozies/new.xml
  def new
    @koozy = Koozy.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @koozy }
    end
  end

  # GET /koozies/1/edit
  def edit
    @koozy = Koozy.find(params[:id])
  end

  # POST /koozies
  # POST /koozies.xml
  def create
    params[:koozy][:style] = Style.find(params[:koozy][:style].to_i)
    @koozy = Koozy.new(params[:koozy])

    respond_to do |format|
      if @koozy.save
        format.html { redirect_to(@koozy, :notice => 'Koozy was successfully created.') }
        format.xml  { render :xml => @koozy, :status => :created, :location => @koozy }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @koozy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /koozies/1
  # PUT /koozies/1.xml
  def update
    @koozy = Koozy.find(params[:id])

    respond_to do |format|
      if @koozy.update_attributes(params[:koozy])
        format.html { redirect_to(@koozy, :notice => 'Koozy was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @koozy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /koozies/1
  # DELETE /koozies/1.xml
  def destroy
    @koozy = Koozy.find(params[:id])
    @koozy.destroy

    respond_to do |format|
      format.html { redirect_to(koozies_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/koozy_tags_controller.rb
class KoozyTagsController < ApplicationController
  # GET /koozy_tags
  # GET /koozy_tags.xml
  def index
    @koozy_tags = KoozyTag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @koozy_tags }
    end
  end

  # GET /koozy_tags/1
  # GET /koozy_tags/1.xml
  def show
    @koozy_tag = KoozyTag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @koozy_tag }
    end
  end

  # GET /koozy_tags/new
  # GET /koozy_tags/new.xml
  def new
    @koozy_tag = KoozyTag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @koozy_tag }
    end
  end

  # GET /koozy_tags/1/edit
  def edit
    @koozy_tag = KoozyTag.find(params[:id])
  end

  # POST /koozy_tags
  # POST /koozy_tags.xml
  def create
    @koozy_tag = KoozyTag.new(params[:koozy_tag])

    respond_to do |format|
      if @koozy_tag.save
        format.html { redirect_to(@koozy_tag, :notice => 'Koozy tag was successfully created.') }
        format.xml  { render :xml => @koozy_tag, :status => :created, :location => @koozy_tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @koozy_tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /koozy_tags/1
  # PUT /koozy_tags/1.xml
  def update
    @koozy_tag = KoozyTag.find(params[:id])

    respond_to do |format|
      if @koozy_tag.update_attributes(params[:koozy_tag])
        format.html { redirect_to(@koozy_tag, :notice => 'Koozy tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @koozy_tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /koozy_tags/1
  # DELETE /koozy_tags/1.xml
  def destroy
    @koozy_tag = KoozyTag.find(params[:id])
    @koozy_tag.destroy

    respond_to do |format|
      format.html { redirect_to(koozy_tags_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  # GET /styles
  # GET /styles.xml
  def index
    @styles = Style.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @styles }
    end
  end

  # GET /styles/1
  # GET /styles/1.xml
  def show
    @style = Style.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @style }
    end
  end

  # GET /styles/new
  # GET /styles/new.xml
  def new
    @style = Style.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @style }
    end
  end

  # GET /styles/1/edit
  def edit
    @style = Style.find(params[:id])
  end

  # POST /styles
  # POST /styles.xml
  def create
    @style = Style.new(params[:style])

    respond_to do |format|
      if @style.save
        format.html { redirect_to(@style, :notice => 'Style was successfully created.') }
        format.xml  { render :xml => @style, :status => :created, :location => @style }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @style.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /styles/1
  # PUT /styles/1.xml
  def update
    @style = Style.find(params[:id])

    respond_to do |format|
      if @style.update_attributes(params[:style])
        format.html { redirect_to(@style, :notice => 'Style was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @style.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.xml
  def destroy
    @style = Style.find(params[:id])
    @style.destroy

    respond_to do |format|
      format.html { redirect_to(styles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.xml
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to(@tag, :notice => 'Tag was successfully created.') }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/koozies_helper.rb
module KooziesHelper
end

app/helpers/koozy_tags_helper.rb
module KoozyTagsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/koozies/_form.html.erb
<%= form_for(@koozy) do |f| %>
  <% if @koozy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@koozy.errors.count, "error") %> prohibited this koozy from being saved:</h2>

      <ul>
      <% @koozy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :style %><br />
    <%= f.text_field :style %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/koozies/edit.html.erb
<h1>Editing koozy</h1>

<%= render 'form' %>

<%= link_to 'Show', @koozy %> |
<%= link_to 'Back', koozies_path %>

app/views/koozies/index.html.erb
<h1>Listing koozies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Style</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @koozies.each do |koozy| %>
  <tr>
    <td><%= koozy.name %></td>
    <td><%= koozy.description %></td>
    <td><%= koozy.style %></td>
    <td><%= link_to 'Show', koozy %></td>
    <td><%= link_to 'Edit', edit_koozy_path(koozy) %></td>
    <td><%= link_to 'Destroy', koozy, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Koozy', new_koozy_path %>

app/views/koozies/new.html.erb
<h1>New koozy</h1>

<%= render 'form' %>

<%= link_to 'Back', koozies_path %>

app/views/koozies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @koozy.name %>
</p>

<p>
  <b>Description:</b>
  <%= @koozy.description %>
</p>

<p>
  <b>Style:</b>
  <%= @koozy.style %>
</p>


<%= link_to 'Edit', edit_koozy_path(@koozy) %> |
<%= link_to 'Back', koozies_path %>

app/views/koozy_tags/_form.html.erb
<%= form_for(@koozy_tag) do |f| %>
  <% if @koozy_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@koozy_tag.errors.count, "error") %> prohibited this koozy_tag from being saved:</h2>

      <ul>
      <% @koozy_tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :koozy %><br />
    <%= f.text_field :koozy %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/koozy_tags/edit.html.erb
<h1>Editing koozy_tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @koozy_tag %> |
<%= link_to 'Back', koozy_tags_path %>

app/views/koozy_tags/index.html.erb
<h1>Listing koozy_tags</h1>

<table>
  <tr>
    <th>Koozy</th>
    <th>Tag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @koozy_tags.each do |koozy_tag| %>
  <tr>
    <td><%= koozy_tag.koozy %></td>
    <td><%= koozy_tag.tag %></td>
    <td><%= link_to 'Show', koozy_tag %></td>
    <td><%= link_to 'Edit', edit_koozy_tag_path(koozy_tag) %></td>
    <td><%= link_to 'Destroy', koozy_tag, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Koozy tag', new_koozy_tag_path %>

app/views/koozy_tags/new.html.erb
<h1>New koozy_tag</h1>

<%= render 'form' %>

<%= link_to 'Back', koozy_tags_path %>

app/views/koozy_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Koozy:</b>
  <%= @koozy_tag.koozy %>
</p>

<p>
  <b>Tag:</b>
  <%= @koozy_tag.tag %>
</p>


<%= link_to 'Edit', edit_koozy_tag_path(@koozy_tag) %> |
<%= link_to 'Back', koozy_tags_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KoozyCollection</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :volume_oz %><br />
    <%= f.text_field :volume_oz %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing style</h1>

<%= render 'form' %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<h1>Listing styles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Volume oz</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @styles.each do |style| %>
  <tr>
    <td><%= style.name %></td>
    <td><%= style.volume_oz %></td>
    <td><%= link_to 'Show', style %></td>
    <td><%= link_to 'Edit', edit_style_path(style) %></td>
    <td><%= link_to 'Destroy', style, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<h1>New style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @style.name %>
</p>

<p>
  <b>Volume oz:</b>
  <%= @style.volume_oz %>
</p>


<%= link_to 'Edit', edit_style_path(@style) %> |
<%= link_to 'Back', styles_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>